export const SHOPIFY_CATEGORY_SEARCH_HINTS: Record<string, string[]> = {
  windows_laptop: ['laptop computer', 'notebook computer'],
  'windows-laptop': ['laptop computer', 'notebook computer'],
  macbook: ['laptop computer', 'notebook computer'],
  iphone: ['mobile phone', 'smartphone'],
  apple_iphone: ['mobile phone', 'smartphone'],
  'apple-iphone': ['mobile phone', 'smartphone'],
  android_phone: ['mobile phone', 'smartphone'],
  'android-phone': ['mobile phone', 'smartphone'],
  ipad: ['tablet computer'],
  android_tablet: ['tablet computer'],
  'android-tablet': ['tablet computer'],
  windows_desktop: ['desktop computer'],
  'windows-desktop': ['desktop computer'],
  custom_gaming_pc: ['desktop computer', 'gaming computer'],
  'custom-gaming-pc': ['desktop computer', 'gaming computer'],
  digital_camera: ['digital camera'],
  'digital-camera': ['digital camera'],
  dslr_camera: ['DSLR camera', 'digital camera'],
  'dslr-camera': ['DSLR camera', 'digital camera'],
  mirrorless_camera: ['mirrorless camera', 'digital camera'],
  'mirrorless-camera': ['mirrorless camera', 'digital camera'],
  action_camera: ['action camera', 'digital camera'],
  'action-camera': ['action camera', 'digital camera'],
  gaming_console: ['video game console'],
  'gaming-console': ['video game console'],
  nintendo_switch: ['video game console'],
  playstation: ['video game console'],
  xbox: ['video game console'],
  monitor: ['computer monitor'],
  internal_hdd: ['hard drive', 'internal hard drive'],
  hdd: ['hard drive', 'internal hard drive'],
  ssd: ['solid state drive', 'SSD'],
  storage_drive: ['hard drive', 'solid state drive'],
  camera: ['digital camera', 'mirrorless camera', 'DSLR'],
  game_console: ['video game console'],
  smartwatch: ['smart watch'],
  networking: ['network router'],
  router: ['network router'],
};

export function searchHintsForInternalCategory(categoryKey: string): string[] {
  return SHOPIFY_CATEGORY_SEARCH_HINTS[categoryKey] || [];
}
